/**
 * @file playwright-codegen.ts
 * @description Generates a Playwright .spec.ts file from recorded session actions.
 */

import type { Session, Action, Bug } from '@shared/types';

function formatDate(ts: number): string {
  return new Date(ts).toISOString().slice(0, 10);
}

function elapsedSec(start: number, ts: number): string {
  return ((ts - start) / 1000).toFixed(1) + 's';
}

function actionToPlaywright(action: Action): string | null {
  switch (action.type) {
    case 'navigation':
      return `  await page.goto('${escapeStr(action.pageUrl)}');`;
    case 'click':
      if (!action.selector) return null;
      return `  await page.click(${selectorExpr(action)});`;
    case 'input':
      if (!action.selector) return null;
      return `  await page.fill(${selectorExpr(action)}, '${escapeStr(action.value ?? '')}');`;
    case 'scroll':
      return null; // scroll actions omitted — too noisy and not reproducible
    default:
      return null;
  }
}

function selectorExpr(action: Action): string {
  const sel = action.selector ?? '';
  // Emit the most readable locator based on strategy
  if (action.selectorStrategy === 'data-testid') {
    const id = sel.match(/\[data-testid="([^"]+)"\]/)?.[1] ?? sel;
    return `page.getByTestId('${escapeStr(id)}')`;
  }
  if (action.selectorStrategy === 'aria-label') {
    const label = sel.match(/\[aria-label="([^"]+)"\]/)?.[1] ?? sel;
    return `page.getByLabel('${escapeStr(label)}')`;
  }
  if (action.selectorStrategy === 'id') {
    const id = sel.replace(/^#/, '');
    return `page.locator('#${escapeStr(id)}')`;
  }
  // role+text or CSS fallback — emit as locator with a fragile comment
  return `page.locator('${escapeStr(sel)}') /* TODO: fragile selector — add data-testid */`;
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Generates a runnable Playwright .spec.ts from session actions with BUG comments.
 */
export function generatePlaywrightSpec(
  session: Session,
  actions: Action[],
  bugs: Bug[]
): string {
  const sortedActions = [...actions].sort((a, b) => a.timestamp - b.timestamp);
  const sortedBugs = [...bugs].sort((a, b) => a.timestamp - b.timestamp);

  const lines: string[] = [];
  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push('');
  lines.push(`// Generated by Refine v1.0.0 — Session: ${session.id}`);
  lines.push(`// Recorded: ${formatDate(session.startedAt)}`);
  lines.push('');
  lines.push(`test('Refine session: ${escapeStr(session.name)} (${formatDate(session.startedAt)})', async ({ page }) => {`);

  if (sortedActions.length === 0) {
    lines.push(`  // No actions were recorded in this session.`);
    if (session.pages.length > 0) {
      lines.push(`  await page.goto('${escapeStr(session.pages[0])}');`);
    }
    lines.push(`});`);
    return lines.join('\n');
  }

  // Track which bugs to insert before each action timestamp
  let bugIdx = 0;
  let lastNavUrl: string | null = null;

  for (const action of sortedActions) {
    // Insert BUG comments for bugs that occurred at or before this action's timestamp
    while (bugIdx < sortedBugs.length && sortedBugs[bugIdx].timestamp <= action.timestamp) {
      const bug = sortedBugs[bugIdx];
      const elapsed = elapsedSec(session.startedAt, bug.timestamp);
      lines.push(`  // BUG: ${bug.priority} — "${escapeStr(bug.title)}" (logged at ${elapsed})`);
      bugIdx++;
    }

    // Auto-insert assertion after navigation
    if (action.type === 'navigation' && lastNavUrl !== null) {
      lines.push(`  await expect(page).toHaveURL(/${escapeRegex(lastNavUrl)}/);`);
    }

    const stmt = actionToPlaywright(action);
    if (stmt) {
      lines.push(stmt);
      lastNavUrl = action.type === 'navigation' ? action.pageUrl : lastNavUrl;
    }
  }

  // Flush remaining bugs after last action
  while (bugIdx < sortedBugs.length) {
    const bug = sortedBugs[bugIdx];
    const elapsed = elapsedSec(session.startedAt, bug.timestamp);
    lines.push(`  // BUG: ${bug.priority} — "${escapeStr(bug.title)}" (logged at ${elapsed})`);
    bugIdx++;
  }

  // Final assertion: last page should be visible
  if (lastNavUrl) {
    lines.push(`  await expect(page).toHaveURL(/${escapeRegex(lastNavUrl)}/);`);
  }

  lines.push(`});`);
  return lines.join('\n');
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
