/**
 * @file playwright-codegen.ts
 * @description Generates a Playwright .spec.ts file from recorded session actions.
 */

import type { Session, Action, Bug } from '@shared/types';
import { VERSION } from '@shared/constants';

function formatDate(ts: number): string {
  return new Date(ts).toISOString().slice(0, 10);
}

function elapsedSec(start: number, ts: number): string {
  return ((ts - start) / 1000).toFixed(1) + 's';
}

function notePrefix(action: Action): string {
  return action.note ? `  // NOTE: ${action.note}\n` : '';
}

function actionToPlaywright(action: Action): string | null {
  switch (action.type) {
    case 'navigation':
      if (!action.value) return null; // skip malformed navigation actions (no destination URL)
      return `${notePrefix(action)}  await page.goto('${escapeStr(action.value)}');`;
    case 'click':
      if (!action.selector) return null;
      return `${notePrefix(action)}${action.selectorConfidence === 'low' ? '  // TODO: low-confidence selector — verify before committing\n' : ''}  await page.locator(${selectorStr(action)}).click();`;
    case 'input':
      if (!action.selector) return null;
      return `${notePrefix(action)}${action.selectorConfidence === 'low' ? '  // TODO: low-confidence selector — verify before committing\n' : ''}  await page.locator(${selectorStr(action)}).fill('${escapeStr(action.value || '')}');`;
    case 'scroll':
      return null; // scroll actions omitted — too noisy and not reproducible
    default:
      return null;
  }
}

/**
 * Returns a single-quoted CSS/attribute selector string for use with
 * page.click(sel) and page.fill(sel, value) — both accept string selectors.
 */
function selectorStr(action: Action): string {
  const sel = action.selector ?? '';
  if (action.selectorStrategy === 'data-testid') {
    const id = sel.match(/\[data-testid="([^"]+)"\]/)?.[1] ?? sel;
    return `'[data-testid="${escapeStr(id)}"]'`;
  }
  if (action.selectorStrategy === 'aria-label') {
    const label = sel.match(/\[aria-label="([^"]+)"\]/)?.[1] ?? sel;
    return `'[aria-label="${escapeStr(label)}"]'`;
  }
  if (action.selectorStrategy === 'id') {
    const id = sel.replace(/^#/, '');
    return `'#${escapeStr(id)}'`;
  }
  return `'${escapeStr(sel)}'`;
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Generates a runnable Playwright .spec.ts from session actions with BUG comments.
 */
export function generatePlaywrightSpec(
  session: Session,
  actions: Action[],
  bugs: Bug[]
): string {
  const sortedActions = [...actions].sort((a, b) => a.timestamp - b.timestamp);
  const sortedBugs = [...bugs].sort((a, b) => a.timestamp - b.timestamp);

  const lines: string[] = [];
  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push('');
  lines.push(`// Generated by Refine ${VERSION} — Session: ${session.id}`);
  lines.push(`// Recorded: ${formatDate(session.startedAt)}`);
  lines.push('');
  lines.push(`test('Refine session: ${escapeStr(session.name)} (${formatDate(session.startedAt)})', async ({ page }) => {`);

  if (sortedActions.length === 0) {
    lines.push(`  // No actions were recorded in this session.`);
    if (session.pages.length > 0) {
      lines.push(`  await page.goto('${escapeStr(session.pages[0])}');`);
      lines.push(`  await page.waitForLoadState('networkidle');`);
    }
    lines.push(`});`);
    return lines.join('\n');
  }

  let bugIdx = 0;

  for (const action of sortedActions) {
    // Insert BUG comments for bugs that occurred at or before this action's timestamp
    while (bugIdx < sortedBugs.length && sortedBugs[bugIdx].timestamp <= action.timestamp) {
      const bug = sortedBugs[bugIdx];
      const elapsed = elapsedSec(session.startedAt, bug.timestamp);
      lines.push(`  // BUG: ${bug.priority} — "${escapeStr(bug.title)}" (logged at ${elapsed})`);
      bugIdx++;
    }

    const stmt = actionToPlaywright(action);
    if (stmt) {
      lines.push(stmt);
      // After each navigation: wait for load and assert URL
      if (action.type === 'navigation' && action.value) {
        lines.push(`  await page.waitForLoadState('networkidle');`);
        lines.push(`  await expect(page).toHaveURL('${escapeStr(action.value)}');`);
      }
    }
  }

  // Flush remaining bugs after last action
  while (bugIdx < sortedBugs.length) {
    const bug = sortedBugs[bugIdx];
    const elapsed = elapsedSec(session.startedAt, bug.timestamp);
    lines.push(`  // BUG: ${bug.priority} — "${escapeStr(bug.title)}" (logged at ${elapsed})`);
    bugIdx++;
  }

  lines.push(`});`);
  return lines.join('\n');
}
