/**
 * @file zip-bundler.ts
 * @description Packages all session exports into a single ZIP file using JSZip.
 */

import JSZip from 'jszip';
import type { Session, Bug, Feature, Action, Screenshot, RecordingChunk } from '@shared/types';
import { generateJsonReport, generateMarkdownReport } from './report-generator';
import { generateReplayHtml } from './replay-bundler';
import { generatePlaywrightSpec } from './playwright-codegen';

/** Generate a README that explains each file and how to use the bundle for bug resolution. */
function generateReadme(
  session: Session,
  bugs: Bug[],
  features: Feature[],
  screenshots: Screenshot[],
  hasReplay: boolean,
): string {
  const lines: string[] = [
    `# Vigil Session Export`,
    ``,
    `**Session:** ${session.name}`,
    `**ID:** ${session.id}`,
    `**Exported:** ${new Date().toISOString()}`,
    ``,
    `---`,
    ``,
    `## File Index`,
    ``,
    `| File | What it is | How to use it |`,
    `|------|-----------|---------------|`,
    `| \`README.md\` | This file | Start here to understand the export |`,
    `| \`report.md\` | Human-readable session report | Open in any Markdown viewer. Contains session stats, pages visited, timeline of actions, bugs found, and feature requests |`,
    `| \`report.json\` | Machine-readable session data | Parse with any JSON tool. Use for automation, CI integration, or feeding into bug trackers |`,
  ];

  if (hasReplay) {
    lines.push(
      `| \`replay.html\` | DOM recording replay | **Open in any browser** (no server needed). Replays the exact user session with mouse movements, clicks, and scrolls. Use the timeline scrubber to jump to specific moments |`,
    );
  }

  lines.push(
    `| \`regression.spec.ts\` | Playwright test spec | Run with \`npx playwright test regression.spec.ts\` to reproduce the session actions automatically. Each bug is marked with a comment so you can see exactly where failures occurred |`,
    `| \`playwright.tsconfig.json\` | TypeScript config for the spec | Companion config so \`tsc --noEmit\` works on the regression spec |`,
  );

  if (screenshots.length > 0) {
    lines.push(
      `| \`screenshots/\` | Captured screenshots (${screenshots.length} files) | Visual evidence of bugs and key moments. Files are numbered in capture order (screenshot-001, 002, etc.) |`,
    );
  }

  lines.push(
    ``,
    `---`,
    ``,
    `## Quick Start: Bug Resolution Workflow`,
    ``,
    `### 1. Understand what happened`,
    ``,
  );

  if (hasReplay) {
    lines.push(
      `Open **\`replay.html\`** in your browser to watch the recorded session. This is a self-contained`,
      `file with no external dependencies — it works fully offline.`,
      ``,
    );
  }

  lines.push(
    `Read **\`report.md\`** for a structured summary with:`,
    `- Session metadata (duration, pages visited, action counts)`,
    `- Chronological timeline of every user action`,
    `- Each bug with severity, description, and linked screenshots`,
    `- Feature requests captured during the session`,
    ``,
    `### 2. Reproduce the bugs`,
    ``,
    `The **\`regression.spec.ts\`** file is a runnable Playwright test that replays the user's actions:`,
    ``,
    '```bash',
    `# Install Playwright (if not already installed)`,
    `npm init -y && npm install -D @playwright/test`,
    `npx playwright install chromium`,
    ``,
    `# Run the regression test`,
    `npx playwright test regression.spec.ts --headed`,
    '```',
    ``,
    `Each bug from the session is annotated in the spec as a comment, so you can see exactly which`,
    `step triggered the issue.`,
    ``,
    `### 3. Fix and verify`,
    ``,
    `After fixing a bug, re-run the regression spec to confirm the fix:`,
    ``,
    '```bash',
    `npx playwright test regression.spec.ts`,
    '```',
    ``,
    `A passing test means the bug is resolved. Commit the spec alongside your fix to prevent regressions.`,
    ``,
  );

  // Bug summary table
  if (bugs.length > 0) {
    lines.push(
      `---`,
      ``,
      `## Bugs Found (${bugs.length})`,
      ``,
      `| # | Severity | Title | Status |`,
      `|---|----------|-------|--------|`,
    );
    bugs.forEach((bug, i) => {
      lines.push(`| ${i + 1} | ${bug.priority} | ${bug.title} | ${bug.status} |`);
    });
    lines.push(``);
  }

  // Feature summary table
  if (features.length > 0) {
    lines.push(
      `## Feature Requests (${features.length})`,
      ``,
      `| # | Title | Status |`,
      `|---|-------|--------|`,
    );
    features.forEach((feat, i) => {
      lines.push(`| ${i + 1} | ${feat.title} | ${feat.status} |`);
    });
    lines.push(``);
  }

  lines.push(
    `---`,
    ``,
    `*Generated by [Vigil](https://github.com/SynaptixLabs/vigil) — Bug Discovery & Resolution Platform*`,
  );

  return lines.join('\n');
}

/**
 * Creates a ZIP bundle containing:
 *   README.md             — how to use this export for bug resolution
 *   replay.html           — self-contained rrweb replay
 *   report.json           — machine-readable session report
 *   report.md             — human-readable session report
 *   regression.spec.ts    — Playwright regression spec
 *   screenshots/          — all captured screenshots as JPEG files
 */
export async function generateZipBundle(
  session: Session,
  bugs: Bug[],
  features: Feature[],
  actions: Action[],
  screenshots: Screenshot[],
  chunks: RecordingChunk[]
): Promise<Blob> {
  const zip = new JSZip();
  const folder = zip.folder(`vigil-${session.id}`)!;

  // Report files
  const jsonReport = generateJsonReport(session, bugs, features, actions, screenshots);
  folder.file('report.json', JSON.stringify(jsonReport, null, 2));
  const mdReport = generateMarkdownReport(session, bugs, features, actions, screenshots);
  folder.file('report.md', mdReport);

  // Replay HTML
  const hasReplay = chunks.length > 0;
  const replayHtml = await generateReplayHtml(session, chunks);
  folder.file('replay.html', replayHtml);

  // Playwright spec + companion tsconfig so consumers can run `tsc --noEmit` on the bundle
  const playwrightSpec = generatePlaywrightSpec(session, actions, bugs);
  folder.file('regression.spec.ts', playwrightSpec);
  folder.file('playwright.tsconfig.json', JSON.stringify({
    compilerOptions: {
      strict: true,
      target: 'ES2020',
      module: 'CommonJS',
      moduleResolution: 'node',
      esModuleInterop: true,
      skipLibCheck: true,
    },
    include: ['*.spec.ts'],
  }, null, 2));

  // Screenshots
  if (screenshots.length > 0) {
    const ssFolder = folder.folder('screenshots')!;
    screenshots.forEach((ss, i) => {
      const base64 = ss.dataUrl.split(',')[1] ?? '';
      const ext = ss.dataUrl.startsWith('data:image/jpeg') ? 'jpg' : 'png';
      const name = `screenshot-${String(i + 1).padStart(3, '0')}.${ext}`;
      ssFolder.file(name, base64, { base64: true });
    });
  }

  // README — how to use this export
  const readme = generateReadme(session, bugs, features, screenshots, hasReplay);
  folder.file('README.md', readme);

  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } });
}
